language: java
dist: bionic
before_install: ant init-ivy
install: ant resolve
#  - sudo apt-get update
#  - sudo apt-get install -y ant-contrib ivy libservlet-api-java
  
jdk: openjdk11
script:
  - cd java
  - ant -f manager-build.xml ivy
  - ant -f manager-build.xml compile

branches:
  only:
    - master-sonarcloud
