language: java
dist: bionic
before_install:
#  - sudo apt-get update
  - sudo apt-get install -y ant-contrib
  
jdk: openjdk11
script:
  ant -f java/manager-build.xml ivy
  ant -f java/manager-build.xml compile

branches:
  only:
    - master-sonarcloud
